addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.0")
addSbtPlugin("com.lightbend.sbt"         % "sbt-javaagent"       % "0.1.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.19")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.3")
